### ISSUE TITLE
 启动 local.js 报错

### ISSUE THREAD

**Issue by Pagliacii** [521xueweihan/shadowsocks-heroku#1]
```
module.js:471
    throw err;
    ^

Error: Cannot find module './merge_sort'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\GitHub\shadowsocks-heroku\encrypt.js:7:16)
    at Object.<anonymous> (G:\GitHub\shadowsocks-heroku\encrypt.js:207:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```
请问如何解决？

**Comment by 521xueweihan** [comment]
你好，是否执行`npm install`命令安装依赖的库？

**Comment by 521xueweihan** [comment]
sorry, 是我忘记上传`merge_sort.js`文件，已修复，请重新 clone 项目或 git pull 获取最新代码 😓

**Comment by Pagliacii** [comment]
thanks

**Comment by rainbowsky911** [comment]
C:\Users\Administrator>node local .js-s rainbowsky911.herokuapp.com-1 1080-m rc4
-k zhang33is -r 80
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\local'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3



你好，可以看一下是我启动local-js地方写错了吗，我太笨看不懂=====谢谢哈

**Comment by 521xueweihan** [comment]
你好，应该是启动命令输入错误，尝试复制、黏贴下面的命令到命令行中：

> node local.js -s rainbowsky911.herokuapp.com -l 1080-m rc4 -k zhang33is -r 80

**Comment by rainbowsky911** [comment]
#11 C:\Users\Administrator>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrato
package.json'
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.

C:\Users\Administrator>node local.js -s rainbowsky911.herokuapp.com -l 1080-m
4 -k zhang33is -r 80
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\Administrator\local.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
帅哥再帮忙看一下吧，第一步就GG了

**Comment by WhirlFirst** [comment]
@521xueweihan 
npm WARN shadowsocks-heroku@0.9.10 No repository field.
npm WARN shadowsocks-heroku@0.9.10 No license field.

第一步就挂了，，，，

**Comment by 521xueweihan** [comment]
@rainbowsky911  @WhirlFirst #19

**Comment by fuguohong** [comment]
安装依赖的时候报错（在项目目录）
npm WARN shadowsocks-heroku@0.9.10 No repository field.
npm WARN shadowsocks-heroku@0.9.10 No license field.
运行时 node local.js -s myvpnapp.herokuapp.com -l 1080-m rc4 -k fff19950728 -r 80
没有任何提示。直接就退出了

**Comment by remember-past** [comment]
这个方法挂了吗？
我全部成功，依然无法使用，而且启用后无法上网

**Comment by 521xueweihan** [comment]
@remember-past 此方法依然有效，请自行。查看配置以及 heroku 服务器的log进行排查问题

**Comment by remember-past** [comment]
非常感谢，已成功

**Comment by LongruiDong** [comment]
注册 Heroku 帐号失败：
网站一直警告：Please confirm you're not a robot.
刷新重新注册也不行orz

**Comment by LongruiDong** [comment]
C:\>node local.js -s dlrapp.herokuapp.com -l 1080 -m rc4 -k dlr3972283169 -r 80
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\local.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

您好，我查找了好几次，还是没找到上面哪里有问题T-T，请问该如何解决？
谢谢哈！

**Comment by 521xueweihan** [comment]
@LongruiDong 安装依赖库有问题

**Comment by LongruiDong** [comment]
@521xueweihan 我又安装了依赖库，执行了：
npm config set registry https://registry.npm.taobao.org
npm info underscore （如果上面配置正确这个命令会有字符串response）后，出现下面很多字符，是安装成功了吧。。
![default](https://user-images.githubusercontent.com/26404032/28665053-e9528106-72f4-11e7-97c4-6e4a91a967a1.JPG)
但下一步启动本地 client，仍然返回
D:\Program Files\nodejs\node_modules\npm>node local.js -s dlrapp.herokuapp.com -
l 1080 -m rc4 -k dlr3972283169 -r 80
module.js:487
    throw err;
    ^

Error: Cannot find module 'D:\Program Files\nodejs\node_modules\npm\local.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

。。。T_T。。。

**Comment by 521xueweihan** [comment]
@LongruiDong  到下 clone 下来的目录下执行命令，找到 local.js 文件

**Comment by yongyecc** [comment]
result = this.cipher.update(buf);
                            ^

TypeError: Cannot read property 'update' of undefined我才装的系统，一直报这个错误

**Comment by jackchen75** [comment]
Couldn't connect to GitHub:
Error:remote was closed,authorization was denied,or an authentication message otherwise not received before the window closed.

大神，这是怎么回事啊

**Comment by xlei1234** [comment]
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }
local connected
concurrent connections: 1
(node:4696) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
local connected
concurrent connections: 2
connecting www.youtube.com via ws://xlssr.herokuapp.com:80/
connecting www.youtube.com via ws://xlssr.herokuapp.com:80/
remote disconnected
remote disconnected
local connected
concurrent connections: 1
connecting www.youtube.com via ws://xlssr.herokuapp.com:80/
remote disconnected

这个怎么解决？

**Comment by HornetsDowney** [comment]
(node:10821) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

![image](https://user-images.githubusercontent.com/47743645/62958541-82dd7980-be29-11e9-97e6-2c5883064990.png)

这个问题很奇怪，因为我这里有两个，我三个月前的命令运行的时候没有这个问题，最近heroku账户忘记了，我重新注册了一个heroku账户后，命令运行的时候就会报这个错。麻烦大佬看一下
