### ISSUE TITLE
四、启动本地client疑问

### ISSUE THREAD

**Issue by DoveBoy** [521xueweihan/shadowsocks-heroku#11]
本人新手，操作到第四步启动本地client完全不知道该怎么操作，楼主第四步教程写的太简略了，新手完全看不懂无从下手，能不能把第四步写的详细一下？需要安装什么软件？提示什么界面才算部署成功？谢谢了！

**Comment by 521xueweihan** [comment]
很抱歉现在才回复。
1. 需要安装 Node.js ：http://www.runoob.com/nodejs/nodejs-install-setup.html
2. npm 是随同 Node.js 一起安装的包管理工具，使用教程：http://www.runoob.com/nodejs/nodejs-npm.html
3. 启动成功显示：`server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }`

**Comment by 521xueweihan** [comment]
也可参考 issues3 ：#3

**Comment by DoveBoy** [comment]
之前在Heroku官网下了一个git工具，但是不能工作，一直报错，不知道什么原因，等会换这个试试，谢谢大神解答

**Comment by 521xueweihan** [comment]
欢迎讨论 😁
