### ISSUE TITLE
没有成功

### ISSUE THREAD

**Issue by Aniderr** [521xueweihan/shadowsocks-heroku#17]
按照您的教程做了，但是依然没有成功，是不是我heroku那边还要做什么操作啊，全程我没有看到一个地方配置账号的呢？

**Comment by 521xueweihan** [comment]
根据您问题的描述我无法定位问题，可以在从头捋一遍教程，第二部分就讲的是 heroku 的设置。
https://github.com/521xueweihan/shadowsocks-heroku#二部署

如还有问题，欢迎继续讨论

**Comment by asahius** [comment]
一～三 顺利部署。
第四步的启动本地 Client的步骤中卡住了。
请问具体怎么操作？

**Comment by 521xueweihan** [comment]
@asahius 请先安装 npm，之后执行第四步的操作

**Comment by Aniderr** [comment]
@521xueweihan  我重新对照了一下教程，每一步都是这样配置的，但是最终浏览器的代理就是不成功，就是不知道为什么？
![image](https://user-images.githubusercontent.com/12654685/27572825-d6132e0e-5b40-11e7-8e90-f95731f26011.png)

**Comment by 521xueweihan** [comment]
@Aniderr 通过你反馈的信息，我无法帮助到你，抱歉。

1. 提供 heroku 上的日志
2. 配置帐号步骤：https://github.com/521xueweihan/shadowsocks-heroku#三设置加密算法和密码
3. 请提供问题的描述：错误信息、有上下文的问题描述

**Comment by asahius** [comment]
@521xueweihan   
已经安装了 Node-v8.1.2-x64的安装包（内带npm）。
请问 步骤四 接下来如何操作？

请问 “进到本项目目录”，具体指的是  本地PC内的目录？还是 Heroku内的目录？
本地的目录的话， 指的 是 github 打包下载下来的“521xueweihan/shadowsocks-heroku” zip文件 解压缩后的文件夹吗？

**Comment by 521xueweihan** [comment]
@asahius 
> github 打包下载下来的“521xueweihan/shadowsocks-heroku” zip文件 解压缩后的文件夹

**Comment by asahius** [comment]
@521xueweihan 
谢谢回复。根据提示，似乎进行到 第四步骤的 第二小步。

提示如下信息。请帮忙看看 是哪里出问题了？
D:\Program Files\shadowsocks-heroku-master>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.

npm WARN shadowsocks-heroku@0.9.10 No repository field.
npm WARN shadowsocks-heroku@0.9.10 No license field.

added 10 packages in 1.781s

D:\Program Files\shadowsocks-heroku-master>node local.js -s vpn-asahi123.herokua
pp.com -l 1080 -m rc4 -k 123456 -r 80
address in use, aborting

D:\Program Files\shadowsocks-heroku-master>

**Comment by 521xueweihan** [comment]
@asahius 建议先重启下电脑，或结束当前进程
> address in use

**Comment by asahius** [comment]
@521xueweihan   电脑重新过了。
重新运行 cmd 命令
先敲入 node
提示>
然后键入local.js -s vpn-asahi123.herokuapp.com -l 1080 -m rc4 -k 123456 -r 80
（注： hiroku 的 app：vpn-ashi123；  加密算法：rc4  ； 密码：123456）
输出的是 SyntaxError: Unexpected identifier

请帮忙看看 我的操作 哪里出问题了？
——————完整的操作下--------
D:\Program Files>cd shadowsocks-heroku-master

D:\Program Files\shadowsocks-heroku-master>node
> local.js -s vpn-asahi123.herokuapp.com -l 1080 -m rc4 -k 123456 -r 80
local.js -s vpn-asahi123.herokuapp.com -l 1080 -m rc4 -k 123456 -r 80
            ^^^

SyntaxError: Unexpected identifier

**Comment by 521xueweihan** [comment]
@asahius 退出 node 再输入命令

npm 是为了安装 本项目运行时需要的库，安装后默认库是全局的，直接执行 教程中的命令

**Comment by asahius** [comment]
@521xueweihan 

似乎成功了。非常感谢！
（之前显示 address in use, aborting， 大概是 开了 Lantern造成端口冲突了。关掉之后，就可以了。）


D:\Program Files\shadowsocks-heroku-master>node local.js -s vpn-asahi123.herokua
pp.com -l 1080 -m rc4 -k 123456 -r 80
address in use, aborting

D:\Program Files\shadowsocks-heroku-master>node local.js -s vpn-asahi123.herokua
pp.com -l 1080 -m rc4 -k 123456 -r 80
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }
local connected
concurrent connections: 1
connecting www.google.co.jp via ws://vpn-asahi123.herokuapp.com:80/
local connected
concurrent connections: 2
local connected
concurrent connections: 3
connecting clients4.google.com via ws://vpn-asahi123.herokuapp.com:80/
connecting www.google.co.jp via ws://vpn-asahi123.herokuapp.com:80/
local connected
concurrent connections: 4
connecting ogs.google.com via ws://vpn-asahi123.herokuapp.com:80/
local connected
concurrent connections: 5
local connected
concurrent connections: 6
local connected
concurrent connections: 7

**Comment by 521xueweihan** [comment]
@asahius 嗯，恭喜。善用 google 是成神之道，加油！

**Comment by 521xueweihan** [comment]
@asahius 密码最好改一下，暴露在给我的描述信息中了。

**Comment by asahius** [comment]
@521xueweihan  
嗯，谢谢提醒。（刚才把 App的名称改了下）。
试用了一下，感觉上google的速度挺快的。

另外，感觉 操作流程的第四步那块， 对于 我这种不懂编程软件的小白菜而言，有些难懂。楼上的Aniderr 也可能是卡在 第四步了。
希望流程能再细化一下比较好。

再次感谢！

**Comment by 521xueweihan** [comment]
@asahius 是的，感谢建议。

主要问题在于，第四步需要安装 npm，不同操作系统步骤不一，所以可能会容易出现问题。

后面，我会整理下第四步骤，使其更加详细、友好 😁

**Comment by asahius** [comment]
@521xueweihan 

吃水不忘挖井人。根据自己的操作，把 第四部的内容（前期准备）稍微 细化了一下。供参考。

【准备工作】
a 在github 的521xueweihan/shadowsocks-heroku页面中的Clone or Download， 选择download zip，解压缩到本地文件夹（建议解压缩后存放D盘，文件名D:\ shadowsocks-heroku）
b 在https://nodejs.org/en/页面， 下载安装 node v8.1.2（含npm）
（windows 系统的情况下）

1.	用CMD命令(Windows OS)进到本项目目录（之前解压缩的zip文件目录），执行npm install 命令，安装依赖的库（如没有 npm ，请自行安装，npm安装依赖慢）
2.	启动本地 client，node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80
3.	启动成功，命令行显示：server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }

**Comment by 521xueweihan** [comment]
@asahius 收到，老铁暖心了！
