### ISSUE TITLE
不能用ss客户端登陆吗？

### ISSUE THREAD

**Issue by xuewill** [521xueweihan/shadowsocks-heroku#18]
必须node启动吗？

**Comment by 521xueweihan** [comment]
是的

**Comment by wisetc** [comment]
$ node local.js -s proxy-shadowsocks.herokuapp.com -l 7070 -m aes-256-cfb -k wzc520 -r 80
server listening at { address: '127.0.0.1', family: 'IPv4', port: 7070 }

但是用shadowsocks就不行，打开一个网页会被下载下来，是因为用的是websocket而不是socket的缘故吗？

**Comment by wisetc** [comment]
$ node local.js -s myproxy-alike.herokuapp.com -l 7070 -m aes-256-cfb -k password -r 80
server listening at { address: '127.0.0.1', family: 'IPv4', port: 7070 }

但是用shadowsocks就不行，打开一个网页会被下载下来，是因为用的是websocket而不是socket的缘故吗？

**Comment by 521xueweihan** [comment]
@wisetc 是的
