### ISSUE TITLE
remote disconnected

### ISSUE THREAD

**Issue by nullptrx** [521xueweihan/shadowsocks-heroku#2]
$ node local.js -s liujunhongz.herokuapp.com -l 1080 -m rc4-md5 -k killer -r 80
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }
local connected
concurrent connections: 1
local connected
concurrent connections: 2
connecting tip.f.360.cn via ws://liujunhongz.herokuapp.com:80/
remote disconnected
local connected
concurrent connections: 2
connecting errsug.se.360.cn via ws://liujunhongz.herokuapp.com:80/
remote disconnected
remote errsug.se.360.cn:80 Error: This socket has been ended by the other party
concurrent connections: 1
remote errsug.se.360.cn:80 Error: This socket has been ended by the other party
concurrent connections: 1
remote tip.f.360.cn:80 error: Error: unexpected server response (503)

**Comment by liujunhongz** [comment]
@521xueweihan

**Comment by nullptrx** [comment]
@521xueweihan #2

**Comment by 521xueweihan** [comment]
你好，

首先，根据你提供的错误信息中的错误代码`503`，我认为可能是你在 heroku 部署项目过程中出错。

然后，我尝试访问`liujunhongz.herokuapp.com`，发现页面提示`An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.`，所以应该是你 heroku 的 shadowsocks-heroku 应用 挂了。

最后，推荐尝试解决问题步骤，请逐一检查😁：
1. 确保你的 shadowsocks-heroku 是最新的（和本项目同步）
2. 查看 heroku 中的 app 运行情况，尝试重启 app
3. 在你的 heroku 中找到错误日志，如果还有问题，可以贴到这里，一起讨论
4. 在GitHub中，删除已 fork 的本项目，重新在heroku中创建一个app，重新部署一遍

很抱歉没有及时回复😅。

**Comment by nullptrx** [comment]
你好，谢谢你得回复。那个503是因为我部署后，通过代理访问，然后导致了应用错误。我重新部署多次，代理访问都会出现把应用给宕掉。我再重新部署，你有空瞧瞧

**Comment by 521xueweihan** [comment]
`node local.js -s liujunhongz.herokuapp.com -l 1080 -m rc4-md5 -k killer -r 80`我这里用你的命令连接，同样也是连接不上，显示 503 错误。

所以，问题应该出在 server 端，如果可以提供 log 日志(访问 https://dashboard.heroku.com/apps/你的app名称/logs 查看日志)，应该能够更好的分析问题

**Comment by nullptrx** [comment]
@521xueweihan 不好意思, 果然是我改错了服务器代码, 现在好了, 谢谢谢谢谢谢. 公司只有一台vpn服务器, 最近浏览器一直出现输入验证码的界面, 网上说可能一个ip一次发请求发太多, 这么多人用, 也难怪, 实在是找不到办法, 看到这个办法, 连上vpn后, 再代理一下, ip就跑美国去了, 巴适得板, 赞!!

**Comment by 521xueweihan** [comment]
解决问题了就好😊
