### ISSUE TITLE
请问一台电脑布置成功了，如果另一台电脑想用必须又要重复第四部，比如安装npm之类的吗？

### ISSUE THREAD

**Issue by uragasit** [521xueweihan/shadowsocks-heroku#23]
新手，请多指教

**Comment by 521xueweihan** [comment]
@uragasit 是的，本地启动 client 需要通过 npm 安装依赖

**Comment by uragasit** [comment]
不知道这个heroku有没有流量限制呢，比如每个月或者每天不能超过多少m？

**Comment by 521xueweihan** [comment]
@uragasit 无流量限制，具体限制如下：
Run apps for free using your monthly pool of free dyno hours
Unverified accounts: receive a pool of 550 free dyno hours
Verified accounts: receive an additional 450 free dyno hours
Dyno hours can be shared across any of your free apps
1 web dyno/1 worker dyno/1 one-off dyno maximum per app
512 MB RAM per dyno
Free apps sleep automatically after 30 mins of inactivity to conserve your dyno hours
Free apps wake automatically when a web request is received
Access to the Heroku Dashboard and Heroku CLI for app management
Custom domains for every free app (with verified account)
Up to 5 free apps (unverified) or 100 (verified)

**Comment by uragasit** [comment]
多谢，这个 a pool of 550 free dyno hours的用量在哪儿查呢，我找了一圈都没看到实时的剩余时间统计，也不知道啥时侯会超时停用

**Comment by 521xueweihan** [comment]
@uragasit 随便用，不会超

> Free apps sleep automatically after 30 mins of inactivity to conserve your dyno hours
