### ISSUE TITLE
四、启动本地 Client的最后一步出错，请教该如何解决？谢谢。

### ISSUE THREAD

**Issue by zhmglp** [521xueweihan/shadowsocks-heroku#24]
之前的步骤都按教主教程做好了，没也见提示出错，但在 四、启动本地 Client    最后一步  node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80（已经把app名称，加密，密码都改成自己设置的了）  出错，提示这样：

module.js:472
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Temp\shadowsocks-heroku-master\local.
js:15:15)
    at Object.<anonymous> (C:\Temp\shadowsocks-heroku-master\local.
js:322:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

请问该怎么办呢？谢谢。

**Comment by 521xueweihan** [comment]
@zhmglp
> Error: Cannot find module 'ws'

这个错误信息的意思是你没有安装 依赖的模块。

1. 用命令行（终端或 cmd），进到上述解压出来的文件夹（目录）
2. 请再次执行 `npm install -g` 命令。

如报错，可以把错误信息复制到这里进行讨论。

**Comment by zhmglp** [comment]
C:\Temp\shadowsocks-heroku-master>npm install -g
C:\Users\Administrator\AppData\Roaming\npm
`-- shadowsocks-heroku@0.9.10
然后再执行 node local.js 这个命令，还是出同样的错。

**Comment by 521xueweihan** [comment]
@zhmglp 你执行 `npm install -g` 命令时，该目录下要有 `package.json` 文件

**Comment by zhmglp** [comment]
下载的zip文件，解压出来就放在C:\Temp\shadowsocks-heroku-master， 请问该在哪个目录下执行 npm install -g 命令呢？

**Comment by zhmglp** [comment]
C:\Temp\shadowsocks-heroku-master目录下有 package.json 这个文件。

**Comment by 521xueweihan** [comment]
@zhmglp 在有 package.json 文件的目录下执行 `npm install -g` 命令

**Comment by zhmglp** [comment]
C:\Temp\shadowsocks-heroku-master 的目录

2017/07/08  20:33    <DIR>          .
2017/07/08  20:33    <DIR>          ..
2017/07/10  13:31               544 .gitignore
2017/07/10  13:31               883 Cakefile
2017/07/10  13:31               231 config.json
2017/07/08  20:33    <DIR>          download
2017/07/10  13:31             5,557 encrypt.js
2017/07/08  20:33    <DIR>          img
2017/07/10  13:31             1,142 LICENSE
2017/07/10  13:31             9,389 local.js
2017/07/10  13:31               868 merge_sort.js
2017/07/10  13:31               262 package.json
2017/07/10  13:31                15 Procfile
2017/07/10  13:31             4,124 README.md
2017/07/10  13:31             5,988 server.js
2017/07/08  20:33    <DIR>          src
2017/07/10  13:31             4,665 test.js
              12 个文件         33,668 字节
               5 个目录  6,434,750,464 可用字节

就在shadowsocks-heroku-master目录执行 npm install -g 命令的。但就是出错。出错信息发到下面一贴吧。

**Comment by 521xueweihan** [comment]
@zhmglp 好

**Comment by zhmglp** [comment]
npm命令执行：
C:\Temp\shadowsocks-heroku-master>npm install -g    
执行后出现下面2行：
C:\Users\Administrator\AppData\Roaming\npm
`-- shadowsocks-heroku@0.9.10

**Comment by zhmglp** [comment]
C:\Temp\shadowsocks-heroku-master>npm install -g
C:\Users\Administrator\AppData\Roaming\npm
`-- shadowsocks-heroku@0.9.10

然后 执行node命令：
C:\Temp\shadowsocks-heroku-master>node local.js -s zhmglp.herokuapp.com -l 1080 -m rc4-md5 -k 12345678 -r 80
出现下面错误：
module.js:472
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Temp\shadowsocks-heroku-master\local.
js:15:15)
    at Object.<anonymous> (C:\Temp\shadowsocks-heroku-master\local.
js:322:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by zhmglp** [comment]
C:\Temp\shadowsocks-heroku-master>node -v
v7.6.0

C:\Temp\shadowsocks-heroku-master>npm -v
4.1.2


原来照你给的连接里面的教程安装7.6.0 x64版本的，出错后卸载安装8.1.3 x64，执行后还是出错，下载安装回7.6.0，但这次是x86的，还是出错。 唉，小白真的难弄好啊。

**Comment by flyerooo** [comment]
同样的错误，错误信息如下
D:\shadowsocks-heroku-master  (shadowsocks-heroku@0.9.10)
λ npm install -g
npm ERR! addLocal Could not install D:\shadowsocks-heroku-master\-
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "-"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path D:\shadowsocks-heroku-master\-
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\shadowsocks-heroku-ma
ster\-'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\shadowsocks-heroku-ma
ster\-'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\shadowsocks-heroku-master\npm-debug.log

**Comment by jwfeng** [comment]
也遇到了...
D:\shadowsocks-heroku-master>npm install -g
npm WARN D:\shadowsocks-heroku-master\node_modules\ws is not a child of C:\Users\xxx\AppData\Roaming\npm
npm ERR! path D:\shadowsocks-heroku-master\node_modules\ws
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'D:\shadowsocks-heroku-master\node_modules\ws' -> 'D:\shadowsocks-heroku-master\node_modules\.ws.DELETE'

**Comment by 521xueweihan** [comment]
@zhmglp @flyerooo @jwfeng  
请用重新在当前目录输入指令：`npm install`

**Comment by 521xueweihan** [comment]
@zhmglp @flyerooo @jwfeng  
请用重新在当前目录输入指令：`npm install`

**Comment by zhmglp** [comment]
C:\Temp\shadowsocks-heroku-master>npm install
执行后显示：
shadowsocks-heroku@0.9.10 C:\Temp\shadowsocks-heroku-master
+-- https-proxy-agent@1.0.0
| +-- agent-base@2.1.1
| | `-- semver@5.0.3
| +-- debug@2.6.8
| | `-- ms@2.0.0
| `-- extend@3.0.1
+-- minimist@1.2.0
`-- ws@1.1.4
  +-- options@0.0.6
  `-- ultron@1.0.2

npm WARN shadowsocks-heroku@0.9.10 No repository field.
npm WARN shadowsocks-heroku@0.9.10 No license field.

**Comment by 521xueweihan** [comment]
@zhmglp 继续按照教程执行启动 client 命令

**Comment by zhmglp** [comment]
执行node命令后出现：
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }

哈哈，是不是大功告成啊？

**Comment by 521xueweihan** [comment]
@zhmglp 这步已完成了，请继续完成教程剩余步骤，最后看到 Google 首页，再来报喜吧。

**Comment by zhmglp** [comment]
成功啦。多谢你不厌其烦地指正和教导！！！

连接很慢，但总可以打开网页。

看cmd窗口总出现断联情况，是不是正常呢，cmd窗口可以关闭吗：
remote disconnected
local connected
concurrent connections: 23
local connected
concurrent connections: 24
local connected
concurrent connections: 25

**Comment by 521xueweihan** [comment]
@zhmglp 可以访问google了吗？

1. cmd 窗口不能关闭，不用的时候再关。
2. 出现断联是正常的，有可能是网络和线路问题
3. 速度慢可以尝试，浏览时只打开一个 tab

**Comment by zhmglp** [comment]
可以访问google了。

好的，非常感谢，刚才cmd窗口内容不动了，也不能输入东西，只能关了，在新窗口再执行node，就可以进google了。

**Comment by 521xueweihan** [comment]
@zhmglp 退出可以在cmd窗口按：`Ctrl+C`

**Comment by jwfeng** [comment]
@521xueweihan 部署成功，但速度太感人...

**Comment by 521xueweihan** [comment]
@jwfeng  
1. 速度慢可以尝试，浏览时只打开一个 tab
2. 和你自己的线路也有关系，可能对外线路不好（是线路不是带宽）

**Comment by zhmglp** [comment]
哦，好的。 
请教： 是不是每次启动win7后都必须打开cmd输入node命令才能科学上网？

**Comment by zhmglp** [comment]
npm install -g 为什么不行而npm install就成功了？

**Comment by 521xueweihan** [comment]
@zhmglp 是的

`-g` 参数是全局的意思，不加默认只是把依赖装在当前目录下，执行完命令你会发现。当前目录下会出现一个 `node_model` 目录。

之所以在 window 下 执行`npm install -g`不成功，我觉得有可能是因为 npm 全局安装的依赖的目录，不在系统 path 下，所以执行启动 client 时，抛出 找不到依赖的错误。

**Comment by zhmglp** [comment]
多谢解答。

已经10.24了，这数字我喜欢。哈哈。

**Comment by zhmglp** [comment]
就是不知道heroku.com能用多久，会不会被墙啊。

**Comment by 521xueweihan** [comment]
@zhmglp 感谢打赏，现在这个方法已经平稳的运行半年了，能撑多久就要看脸了。

**Comment by jwfeng** [comment]
@521xueweihan 工作环境电信线路，下班了回去联通网络试试看怎么样。
