### ISSUE TITLE
按照说明配置成功，但无法连接网络

### ISSUE THREAD

**Issue by flyerooo** [521xueweihan/shadowsocks-heroku#25]
按照说明配置成功，唯一不同点是port改为1082，SwitchyOmega也改为1082（因为1080已结在别的ss中使用），无法连接成功
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1082 }
local connected                      
concurrent connections: 1            
local connected                      
concurrent connections: 2            
local connected                      
concurrent connections: 3            
local connected                      
concurrent connections: 4            
local connected                      
concurrent connections: 5            
local connected                      
concurrent connections: 6            
local connected                      
concurrent connections: 7            
local connected                      
concurrent connections: 8            
local connected                      
concurrent connections: 9            
local connected                      
concurrent connections: 10           
local disconnected                   
concurrent connections: 9            
local connected                      
concurrent connections: 10           
local disconnected                   
concurrent connections: 9

**Comment by 521xueweihan** [comment]
@flyerooo 检查协议、启动命令

我本地测试，修改本地端口，没有问题。

**Comment by flyerooo** [comment]
node local.js -s sshero.herokuapp.com -l 1082 -m aes-256-cfb -k 密码 -r 80
启动命令检查没发现说明问题，请问还能检查哪儿吗？

**Comment by flyerooo** [comment]
已确认为SwitchyOmega 协议设置不正确，谢谢

**Comment by flyerooo** [comment]
已确认为SwitchyOmega 协议设置不正确，谢谢
