### ISSUE TITLE
安卓手机怎样才能用这个呢？谢谢。

### ISSUE THREAD

**Issue by zhmglp** [521xueweihan/shadowsocks-heroku#26]

**Comment by 521xueweihan** [comment]
@zhmglp 暂时客户端（Android和IOS）不支持在云平台（heroku）搭建的ss

**Comment by zhmglp** [comment]
好的，谢谢。如果又开发新好玩的，请多多分享啊。

**Comment by 521xueweihan** [comment]
@zhmglp 好的，可以关注我的 [HelloGitHub](https://hellogithub.com) 网站 😁

**Comment by 521xueweihan** [comment]
@zhmglp 
https://github.com/shadowsocks/shadowsocks-android/issues/1276#issuecomment-318885372
> Implemented in 4.2.0. Will be released soon.

ss 的 android 客户端将在 4.2.0 版本 支持

**Comment by simonsmh** [comment]
那个只是导入在线acl规则，有点类似于在线导入pac罢了，你理解错了
