### ISSUE TITLE
npm install 问题

### ISSUE THREAD

**Issue by sundawei1996** [521xueweihan/shadowsocks-heroku#28]
一安装就出现npm WARN shadowsocks-heroku@0.9.10 No repository field 
npm WARN shadowsocks-heroku@0.9.10 No license field.

**Comment by 521xueweihan** [comment]
@sundawei1996 请确定执行 `npm install` 命令时，当前目录下有 `LICENSE` 等文件。（切换到master分支)

**Comment by 521xueweihan** [comment]
@sundawei1996 请确定执行 `npm install` 命令时，当前目录下有 `LICENSE` 等文件。（切换到master分支)
