### ISSUE TITLE
shadowsocks-heroku 有没有android版

### ISSUE THREAD

**Issue by scljy** [521xueweihan/shadowsocks-heroku#29]
shadowsocks-heroku 有没有android版

**Comment by onplus** [comment]
这两个软件可以在安卓运行nodejs
https://play.google.com/store/apps/details?id=io.tempage.dorynode

https://play.google.com/store/apps/details?id=com.termux

https://apkpure.com/

**Comment by scljy** [comment]
怎么用呢？

**Comment by onplus** [comment]
dory ：https://github.com/onplus/shadowsocks-heroku/issues/7

termux当成linux用
https://github.com/mrluanma/shadowsocks-heroku
https://medium.freecodecamp.org/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f
https://jingsam.github.io/2017/02/07/nodejs-on-android.html

**Comment by wojiaoluyuan** [comment]
有空我录个视频吧，先上普通教程的视频
https://www.youtube.com/watch?v=Aro55ygbx58
