### ISSUE TITLE
感谢大神，成功运行，只是速度有些慢。

### ISSUE THREAD

**Issue by jerry011235** [521xueweihan/shadowsocks-heroku#3]
1.速度有些慢。看youtube 最高在500KB/S（20M宽带，无其他代理配合），也是时不时remote disconnected
2.对于小白来讲（我就是），还需要提前下载安装好两个东西：
①[Download and run the Windows installer.](https://devcenter.heroku.com/articles/heroku-cli)
②[node-v6.9.2-x64.msi](https://nodejs.org/en/)
`启动本地 client`是说 在Clone的项目文件夹里右键，选择`get bash here`，然后输入`node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80`

**Comment by 521xueweihan** [comment]
大神不敢当，我只是分享了一下。

非常感谢🙏，提供本教程中的不足，如有遇到类似疑惑，我将在 error 中直接引入你提供的步骤😃

**Comment by tonny0812** [comment]
可用，速度跟自己的VPS相比还是慢点，不过非常支持你的分享精神，赞~~

**Comment by 521xueweihan** [comment]
🙏  感谢支持
