### ISSUE TITLE
求助，执行npm install时出现问题了

### ISSUE THREAD

**Issue by huangsanm** [521xueweihan/shadowsocks-heroku#30]
`
npm WARN shadowsocks-heroku@0.9.10 No repository field.
npm WARN shadowsocks-heroku@0.9.10 No license field.
`

启动本地client时出现：
node local.js -s xxx.herokuapp.com -l 1080 -m xxx -k xxx -r 80
出现：
address in use, aborting

**Comment by 521xueweihan** [comment]
端口被占用，请查看 1080 端口
