### ISSUE TITLE
Why do u set the remote port to '80' when starting local.js

### ISSUE THREAD

**Issue by alexya** [521xueweihan/shadowsocks-heroku#31]
`node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80`

大兄弟，想请教一个问题。

这里，启动local.js时，指定的远程端口是`80`，server.js 监听的是8080端口，而且，herokuapp提供的URL也是https（那就是`443`端口）。所以，为什么你的客户端指定80端口，可以正常工作，而指定443或者8080反而不能工作？

我尝试着把这个项目部署到非heroku的另外一个服务商zeit.co, e.g. `https://alex-ssr-naobaigshf.now.sh/`，直接打开这个链接，能够看到服务器正常启动了（你可以直接点开试试）。

但是，这次，就不能正常工作了。
`"C:\Program Files\nodejs\node.exe" local.js -s alex-ssr-naobaigshf.now.sh -l 1080 -m aes-256-cfb -k barfoo! -r 80`
这里，远程端口设置不论是80，443还是8080，都无法正常工作。

没有你的联系试，所以在这里问一下。如果“不方便”，就直接删除吧。
如果方便，能否帮忙看看或者解释一下，这个server.js到底怎么工作的？我看了一下源代码，并没有找到哪里有443端口接收到的内容转到8080端口。

p.s.
我是一个很传统的桌面应用老码农，对网络编程不是很懂。
通读完代码，我觉得理论上，你这个server应该能在所有支持`http/https`的网络服务上运行。

**Comment by onplus** [comment]
连接是websocket 不是http/https

端口是由heroku控制的 process.env.PORT

**Comment by alexya** [comment]
@onplus 我搜索了一下代码，只有一个地方有这个`process.env.PORT`，例如：
```
  if (process.env.PORT) {
    config['remote_port'] = +process.env.PORT;
  }
```
你的意思是，这个`process.env.PORT`是在heroku的系统环境里面的？

我在本地起了一个server.js，debug了一下，这个port值就是`8080`，也就是在config.json里面设置的啊？而且，本地起 server.js，再起一个local.js，不能用`80`连接server，只能用`8080`连接。

看来，heroku环境里做了些啥？

但，我还是没理解。heroku怎么把发到`80`的数据转给`8080`的？

thx a lot.

**Comment by onplus** [comment]
你可以试试
  "scheme": "wss",
  "remote_port": 443,

**Comment by alexya** [comment]
@onplus 
I set the config.json of the server  as what you said, 
```
{
  "server": "127.0.0.1",
  "local_address": "127.0.0.1",
  "scheme": "wss",
  "local_port": 1080,
  "remote_port": 443,
  "password": "barfoo!",
  "timeout": 600,
  "method": "aes-256-cfb"
}
```

Then I tried to deploy a new app to zeit.co, you can take a look at it from https://alex-ssr-epbhtwldbe.now.sh/

the client is using `node local.js -s alex-ssr-epbhtwldbe.now.sh -l 1080 -m aes-256-cfb -k barfoo! -r 80` or use `-r 443` port, but both failed. 
e.g. 
when using `-r 80`
![image](https://user-images.githubusercontent.com/2831220/33051973-93e3c20c-cea7-11e7-84c2-3aef1fac9ede.png)

when using `-r 443` 
![image](https://user-images.githubusercontent.com/2831220/33052044-dffac5f0-cea7-11e7-8649-59b5d1455e1f.png)

Furthermore, I joined the slack channel of zeit.co and asked them for help. the comment I got is as follows. But I didn't understand it. 
![image](https://user-images.githubusercontent.com/2831220/33052121-4a873264-cea8-11e7-841c-daa4c8ed0ab0.png)
![image](https://user-images.githubusercontent.com/2831220/33052134-54437164-cea8-11e7-913b-e6d294e57720.png)

**Comment by onplus** [comment]
服务端不用改

本地执行 `node local.js -c local-config.json`

 local-config.json内容
{
  "server": "alex-ssr-epbhtwldbe.now.sh",
  "local_address": "127.0.0.1",
  "scheme": "wss",
  "local_port": 1080,
  "remote_port": 443,
  "password": "barfoo!",
  "timeout": 600,
  "method": "aes-256-cfb"
}

**Comment by onplus** [comment]
可以用在telegram上
![image](https://user-images.githubusercontent.com/31188782/33053085-c7c34840-ceac-11e7-86e9-bcebfd6dc202.png)

**Comment by 521xueweihan** [comment]
@alexya 请勿在此提问
@onplus 如果方便请移除，参考教程的连接。
