### ISSUE TITLE
怎么进到本项目目录？

### ISSUE THREAD

**Issue by cctvass** [521xueweihan/shadowsocks-heroku#6]
请问怎么 “进到本项目目录”

需要运行什么程序吗？有没有更详细的图文教程?

**Comment by 521xueweihan** [comment]
“进到本项目目录”：
- window，进入clone下来的文件夹
- linux or mac，使用 cd 命令，打开clone下来的文件夹

关于clone：
Clone 本项目：`git clone https://github.com/521xueweihan/shadowsocks-heroku.git`

**Comment by cctvass** [comment]
请问这个 clone 是点网页还是什么东西

还是Heroku Toolbelt？

**Comment by cctvass** [comment]
大神 有没有QQ群？ 这问太慢！

**Comment by 521xueweihan** [comment]
clone：点击本项目网页，右边绿色“Clone or download”按钮，获取地址，然后在本地使用 git 工具的`clone`命令

**Comment by 521xueweihan** [comment]
[Git入门教程](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)

**Comment by cctvass** [comment]
每次使用都要启用本地client打命令？能用Shadowsocks吗？

**Comment by 521xueweihan** [comment]
- 每次启动都需要输入启动指令。可以自己写个脚本，便于启动。
- 因为使用的是 websocket 协议，不同于 Shadowsocks 客户端，所以不能用 Shadowsocks 客户端

**Comment by cctvass** [comment]
这个速度真的好慢,有没有加速的方法？ net-speeder能用吗？

**Comment by 521xueweihan** [comment]
没有，heroku提供的不是主机，是云平台
