### ISSUE TITLE
启动本地 client 是在哪里？

### ISSUE THREAD

**Issue by dexterlee1993** [521xueweihan/shadowsocks-heroku#7]
启动本地 client 是什么意思，我每次使用都要在git 里输入node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80这个才行，我做的对吗？

**Comment by 521xueweihan** [comment]
是的，你做的没错。

如果不想每次都是输输入这么多命令，可以写一个 shell 脚本，每次就运行哪个脚本就行了

**Comment by 521xueweihan** [comment]
1.创建脚本命名为：vpn.sh，内容如下：

```sh
cd /项目所在的绝对路径

node local.js -s 你的app名称.herokuapp.com -l 1080 -m 设置的加密算法 -k 设置的密码 -r 80
```

2.因为我用的shell是 zsh，所以我就在`.zshrc`文件的末尾加了下面的内容（默认是`.bashrc`）

```
alias vpn="/上面脚本所在位置的绝对路径/vpn.sh"
```

3.以后只要你在 终端中输入命令：`vpn`，就可以启动了

**Comment by dexterlee1993** [comment]
谢谢大神，不过我第二条写绝对路径最后怎么都启动不了，然后我把第二条那个改成相对路径然后成功了。

**Comment by 521xueweihan** [comment]
你好，

修改完`.zshrc`后需要重新打开终端，新的配置才会生效。是不是有可能你配置完绝对路径后，没有重新打开终端？

**Comment by dexterlee1993** [comment]
那个我是小白一个，我找不到.zshrc但是找到了.bashrc然后我就在.bashrc后边加了一句，然后写的是绝对路径不管用，然后我把脚本拖到git里发现出来的是相对路径，我就改成了相对路径就成功了。我什么也不懂反正瞎搞就搞好了😂

**Comment by 521xueweihan** [comment]
嗯，好的，加油。
