### ISSUE TITLE
能不能用 sslocal 来运行？

### ISSUE THREAD

**Issue by beautifulzyb** [521xueweihan/shadowsocks-heroku#9]
我刚按照您给的布置了heroku，在ubuntu系统下 client我用的是sslocal命令，不知道为什么，无法运行啊，在您给的命令行中 -s 是服务器地址，-l 是本地端口， -k 是密码 ， -m 是加密方式 ，但是我不知道 -r 是什么意思，也不知道怎么更改，它是指服务器的端口吗？

**Comment by 521xueweihan** [comment]
您好，

1. -r 参数就是指服务器的端口
2. 我不了解 sslocal 命令，所以不知道具体执行命令。有一点，本项目 和 shadowsocks 不同的是 shadowsocks-heroku 使用的 WebSocket 代替原本的 sockets。（传输协议不同，所以客户端只能用本项目提供的）

**Comment by 521xueweihan** [comment]
可以编写脚本，通过命令启动，细节可以参考：#7
